// config.bin - 15:15:31 07/24/14, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class ML_Functions {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"A3_Functions_F"};
	};
};

//---Mission classes---
#include <CFG\CfgPermits.hpp>
#include <CFG\CfgEmporiums.hpp>
//---

//---Functions---
#include <CFG\CfgFunctions.hpp>
//---